"""create users and wallets

Revision ID: a358043160c4
Revises: 
Create Date: 2026-06-29 20:12:20.654092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a358043160c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный номер пользователя'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Фамилия пользователя'),
    sa.Column('middle_name', sa.String(), nullable=True, comment='Отчество пользователя'),
    sa.Column('email', sa.String(), nullable=False, comment='Электронная почта пользователя'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Дата создания профиля'),
    sa.Column('password_hash', sa.String(), nullable=False, comment='Хеш пароля'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Уникальный ключ кошелька'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Уникальный ключ пользователя этого кошелька'),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True, comment='Текущий баланс счёта'),
    sa.Column('currency', sa.String(), nullable=True, comment='Валюта'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_wallets_uuid'), 'wallets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_uuid'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
