"""add transfer

Revision ID: fa090332df41
Revises: a358043160c4
Create Date: 2026-08-18 16:23:01.674622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa090332df41'
down_revision: Union[str, Sequence[str], None] = 'a358043160c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_wallet_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('to_wallet_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Numeric(10, 2), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True, server_default='completed'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.uuid'], ),
        sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.uuid'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_id', 'transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
